# Generated by Django 4.1 on 2023-07-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producciondiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=40)),
                ('setpoint', models.FloatField(default=0)),
                ('op1', models.FloatField(default=0)),
                ('op2', models.FloatField(default=0)),
                ('op3', models.FloatField(default=0)),
                ('op4', models.FloatField(default=0)),
                ('op5', models.FloatField(default=0)),
                ('op6', models.FloatField(default=0)),
                ('op7', models.FloatField(default=0)),
                ('op8', models.FloatField(default=0)),
                ('op9', models.FloatField(default=0)),
                ('op10', models.FloatField(default=0)),
                ('op11', models.FloatField(default=0)),
                ('op12', models.FloatField(default=0)),
                ('op13', models.FloatField(default=0)),
                ('op14', models.FloatField(default=0)),
                ('op15', models.FloatField(default=0)),
                ('op16', models.FloatField(default=0)),
                ('op17', models.FloatField(default=0)),
                ('op18', models.FloatField(default=0)),
                ('op19', models.FloatField(default=0)),
                ('op20', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('Editable', models.BooleanField(default=False)),
            ],
        ),
    ]
