# Generated by Django 4.1 on 2023-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='idlote',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='idlote'),
        ),
    ]
