# Generated by Django 4.1 on 2023-04-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_operaciones_idlote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operaciones',
        ),
    ]
