# Generated by Django 4.1 on 2023-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_operaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlote', models.BigIntegerField(blank=True, null=True, verbose_name='idlote')),
                ('hora', models.CharField(blank=True, max_length=20, null=True, verbose_name='hora')),
                ('hora_fin', models.CharField(blank=True, max_length=20, null=True, verbose_name='hora_fin')),
                ('em1_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em1_time')),
                ('em1', models.FloatField(blank=True, null=True, verbose_name='em1')),
                ('em2_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em2_time')),
                ('em2', models.FloatField(blank=True, null=True, verbose_name='em2')),
                ('em3_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em3_time')),
                ('em3', models.FloatField(blank=True, null=True, verbose_name='em3')),
                ('em4_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em4_time')),
                ('em4', models.FloatField(blank=True, null=True, verbose_name='em4')),
                ('em5_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em5_time')),
                ('em5', models.FloatField(blank=True, null=True, verbose_name='em5')),
                ('em6_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em6_time')),
                ('em6', models.FloatField(blank=True, null=True, verbose_name='em6')),
                ('em7_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em7_time')),
                ('em7', models.FloatField(blank=True, null=True, verbose_name='em7')),
                ('em8_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em8_time')),
                ('em8', models.FloatField(blank=True, null=True, verbose_name='em8')),
                ('em9_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='em9_time')),
                ('em9', models.FloatField(blank=True, null=True, verbose_name='em9')),
            ],
        ),
    ]
