# Generated by Django 4.1 on 2023-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_operaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='em_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='em')),
                ('ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID_ingrdiente')),
                ('Ingrediente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ingrdiente')),
                ('SP', models.FloatField(blank=True, null=True, verbose_name='sp')),
            ],
        ),
    ]
