# Generated by Django 4.1 on 2023-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_em_sp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='em_sp',
            name='em',
            field=models.IntegerField(blank=True, null=True, verbose_name='em'),
        ),
    ]
