# Generated by Django 4.1 on 2023-04-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_em_sp_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='em_sp',
            name='ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID_ingrediente'),
        ),
        migrations.AlterField(
            model_name='em_sp',
            name='Ingrediente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ingrediente'),
        ),
    ]
