# Generated by Django 4.1 on 2023-07-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_em_sp_id_alter_em_sp_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='em10',
            field=models.FloatField(blank=True, null=True, verbose_name='em10'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em10_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em10_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em11',
            field=models.FloatField(blank=True, null=True, verbose_name='em11'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em11_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em11_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em12',
            field=models.FloatField(blank=True, null=True, verbose_name='em12'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em12_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em12_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em13',
            field=models.FloatField(blank=True, null=True, verbose_name='em13'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em13_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em13_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em14',
            field=models.FloatField(blank=True, null=True, verbose_name='em14'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em14_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em14_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em15',
            field=models.FloatField(blank=True, null=True, verbose_name='em15'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em15_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em15_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em16',
            field=models.FloatField(blank=True, null=True, verbose_name='em16'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em16_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em16_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em17',
            field=models.FloatField(blank=True, null=True, verbose_name='em17'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em17_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em17_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em18',
            field=models.FloatField(blank=True, null=True, verbose_name='em18'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em18_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em18_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em19',
            field=models.FloatField(blank=True, null=True, verbose_name='em19'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em19_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em19_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em20',
            field=models.FloatField(blank=True, null=True, verbose_name='em20'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em20_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em20_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em21',
            field=models.FloatField(blank=True, null=True, verbose_name='em21'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='em21_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='em21_time'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='humedad',
            field=models.FloatField(blank=True, null=True, verbose_name='humedad'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='ph'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='receta_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='receta_id'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='receta_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='receta_nombre'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='receta_total_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='receta_total_kg'),
        ),
        migrations.AlterField(
            model_name='productionorders1_sap',
            name='plannedqty',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=40, null=True, verbose_name='PlannedQty'),
        ),
        migrations.AlterField(
            model_name='productionorders2_sap',
            name='plannedqty',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=40, null=True, verbose_name='PlannedQty'),
        ),
    ]
