# Generated by Django 4.1 on 2023-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_operaciones_em10_operaciones_em10_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='idfabricacion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='idfabricacion'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='receta_total_set_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='receta_total_set_kg'),
        ),
    ]
